exports.tasksListPage = function(tasks, d, task){
    var pagHTML = `
    <!DOCTYPE html>
    <html>
        <head>
            <meta charset="UTF-8"/>
            <link rel="icon" href="favicon.png"/>
            <link rel="stylesheet" href="w3.css"/>
            <title>Gestor de Tarefas</title>
        </head>
        <body>
            <div class="w3-card-4">
                <header class="w3-container w3-cyan w3-text-white">
                    <h1>Task List</h1>
                </header>

                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Form</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id"/>
                        <label>Due Date</label>
                        <input class="w3-input w3-round" type="date" name="due_date"/>
                        <label>Who</label>
                        <input class="w3-input w3-round" type="text" name="who"/>
                        <label>What</label>
                        <input class="w3-input w3-round" type="text" name="what"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-cyan w3-text-white w3-mb-2 w3-round-large" type="submit">Submit</button>
                </form>
                <br/>
            `

        if (task){
            pagHTML += `
                <form class="w3-container" method="POST">
                    <fieldset>
                        <legend>Edit</legend>
                        <label>Id</label>
                        <input class="w3-input w3-round" type="text" name="id" readonly value="${task.id}"/>
                        <label>Task</label>
                        <input class="w3-input w3-round" type="text" name="what" value="${task.what}"/>
                        <label>Due Date</label>
                        <input class="w3-input w3-round" type="date" name="due_date" value="${task.due_date}"/>
                        <label>Who</label>
                        <input class="w3-input w3-round" type="text" name="who" value="${task.who}"/>
                    </fieldset>
                    <br/>
                    <button class="w3-btn w3-cyan w3-text-white w3-mb-2 w3-round-large" type="submit">Submit</button>
                </form>
                <br/>
                `
        }
        
    pagHTML += `
                <div name"to-do" class="w3-container" style="padding-right: 50%">
                    <table class="w3-table-all">
                        <tr>
                            <th>Task</th>
                            <th>Due Date</th>
                            <th>Who</th>
                        </tr>
                `
            for(let i = 0; i < tasks.length ; i++){
                pagHTML += `
                        <tr>
                            <td>${tasks[i].what}</td>
                            <td>${tasks[i].due_date}</td>
                            <td>${tasks[i].who}</td>
                            <td>
                                <a href="tasks/edit/${tasks[i].id}" style="text-decoration: none">
                                    <button class="w3-btn w3-cyan w3-text-white w3-mb-2 w3-round-large" type="submit">Edit</button>
                                </a>
                                <a href="tasks/done/${tasks[i].id}" style="text-decoration: none">
                                    <button class="w3-btn w3-cyan w3-text-white w3-mb-2 w3-round-large" type="submit">Done</button>
                                </a>
                            </td>
                        </tr>
                `
            }

    pagHTML += `
                    </table>
                </div>
                
                <div name"done" class="w3-container" style="padding-left: 50%">
                    <table class="w3-table-all">
                        <tr>
                            <th>Task</th>
                            <th>Due Date</th>
                            <th>Who</th>
                        </tr>
            `
            for(let i = 0; i < tasks.length ; i++){
                pagHTML += `
                        <tr>
                            <td>${tasks[i].what}</td>
                            <td>${tasks[i].due_date}</td>
                            <td>${tasks[i].who}</td>
                        </tr>
                `
            }
        

    pagHTML += `
                    </table>
                </div>
                <br/>
                <footer class="w3-container w3-cyan w3-text-white">
                    <h5>Generated by EngWeb2023 in ${d}</h5>
                </footer>
            </div>
        </body>
    </html>
    `
    return pagHTML
}


// ---------------Student's Page--------------------------------
// Change and adapt to current dataset...
exports.taskPage = function( aluno, d ){
    var pagHTML = `
    <html>
    <head>
        <title>Aluno: ${aluno.Id}</title>
        <meta charset="utf-8"/>
        <link rel="icon" href="favicon.png"/>
        <link rel="stylesheet" href="w3.css"/>
    </head>
    <body>
        <div class="w3-card-4">
            <header class="w3-container w3-cyan w3-text-white">
                <h1>Aluno ${aluno.id}</h1>
            </header>

            <div class="w3-container">
                <ul class="w3-ul w3-card-4" style="width:50%">
                    <li><b>Nome: </b> ${aluno.nome}</li>
                    <li><b>Número: </b> ${aluno.id}</li>
                    <li><b>Git (link): </b> <a href="${aluno.gitlink}">${aluno.gitlink}</a></li>
                </ul>
            </div>
            <div class="w3-container w3-margin-8">
                <ul class="w3-ul">
            `
            for(let i=1; i < 9; i++){
                key = `tpc${i}`
                if(key in aluno){
                    pagHTML += `
                        <li><b>TPC${i}</b></li>
                    `
                }
            }
    

    pagHTML +=     `</ul></div>
            <footer class="w3-container w3-cyan w3-text-white">
                <address>Gerado por galuno::RPCW2022 em ${d} - [<a href="/">Voltar</a>]</address>
            </footer>
        </div>
    </body>
    </html>
    `
    return pagHTML
}


exports.errorPage = function(errorMessage, d) {
    return `
    <p> ${d}: Error: ${errorMessage}</p>
    `
}